server:
  servlet:
    context-path:
  port: 8081

spring:
  application:
    name:
      nu-map-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nu-map}?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true